### ISSUE TITLE
Error: panic: send to closed channel

### ISSUE THREAD

**Issue by jonnylangefeld** [Azure/azure-event-hubs-go#142]
_Originally posted by @jonnylangefeld in https://github.com/Azure/azure-event-hubs-go/pull/137#issuecomment-528029362_

This current release actually does sometimes write to a closed channel now:

```
panic: send on closed channel

goroutine 616518 [running]:
github.com/Azure/azure-event-hubs-go/v2/storage.(*LeaserCheckpointer).GetLeases.func1(0xc0002766c0, 0xc003a5c330, 0xc001374780, 0xc0004631a6, 0x2)
	/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v2@v2.0.2/storage/storage.go:199 +0x15a
created by github.com/Azure/azure-event-hubs-go/v2/storage.(*LeaserCheckpointer).GetLeases
	/go/pkg/mod/github.com/!azure/azure-event-hubs-go/v2@v2.0.2/storage/storage.go:197 +0x258
```

sorry, no solution yet. 
@devigned do you know why that could happen? To me your suggestion with the switch case seemed totally valid. Also [this blog post](https://blog.golang.org/context) sound like `ctx.Error()` will only be called after the empty struct was sent to the done channel. 

I'll run more tests and compare it to the solution with the `if` clause I proposed originally. Feel free to make other suggestions.

**Comment by jonnylangefeld** [comment]
@gavinfish @devigned, thanks for fixing this! Do you have an ETA of when this will be released?
